# Generated by Django 5.0 on 2023-12-05 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperMc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=300)),
                ('firebase_key', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Super Mc',
            },
        ),
    ]
