# Generated by Django 5.0 on 2023-12-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supermc',
            old_name='firebase_key',
            new_name='key',
        ),
    ]
