# Generated by Django 5.0 on 2024-01-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_rename_firebase_key_supermc_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supermc',
            old_name='password',
            new_name='login_password',
        ),
        migrations.AddField(
            model_name='supermc',
            name='login_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
